### ISSUE TITLE
Ubuntu 14.04 - make install error - Homebrew on Linux

### ISSUE THREAD

**Issue by SeyVaneerdewegh** [ONEAgency/drupical#12]
Running 'make install' on an ubuntu 14.04 as host machine throws following error:

```
drupical (master *+=)$ make install
Installing Homebrew.
$(curl -sS https://raw.githubusercontent.com/Homebrew/install/master/install | ruby)
See Linuxbrew: http://brew.sh/linuxbrew/
make: *** [install-homebrew] Error 1
```

**Comment by SeyVaneerdewegh** [comment]
Installing Linuxbrew fixes this.

https://github.com/Homebrew/linuxbrew

**Comment by SeyVaneerdewegh** [comment]
We can do the following:
Support the install of Homebrew and Linuxbrew in the make file.
Or remove the install of Homebrew from the make file and add Homebrew/Linuxbrew to the dependencies of the project.

**Comment by LeShadow** [comment]
I'll integrate the linuxbrew in the makefile.
