### ISSUE TITLE
Varnish installation failed

### ISSUE THREAD

**Issue by kimkennof-dp** [ONEAgency/drupical#16]
==> default: STDERR: dpkg-statoverride: error: error setting ownership of `/var/log/varnish': Operation not permitted

==> default: dpkg: error processing varnish (--configure):
==> default:  subprocess installed post-installation script returned error exit status 2
==> default: Errors were encountered while processing:
==> default:  varnish
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: ---- End output of apt-get -q -y install varnish=3.0.7-1~precise ----
==> default: Ran apt-get -q -y install varnish=3.0.7-1~precise returned 100
==> default: [2015-04-10T08:10:32+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
make: **\* [vagrant-up] Error 1

**Comment by klaasvw** [comment]
Temporary solution is deleting the logs/varnish directory before reprovisioning.
