### ISSUE TITLE
cleanup makefile

### ISSUE THREAD

**Issue by barickx** [ONEAgency/drupical#37]

**Comment by barickx** [comment]
kun jij dit valideren voor mij? zit gemerged in master en issue ticket 37

**Comment by klaasvw** [comment]
Looking good! Thanks.

**Comment by klaasvw** [comment]
Added the following fixes:
- Fix exit codes bug: When the make file exists after an error it keeps running
- Librarian will be installed automatically if it doesn't exist
- Put back the check if a plugin is already installed
- Fixed a loop bug when the .vagrant dir didn't exist yet
