### ISSUE TITLE
Check Vagrant version

### ISSUE THREAD

**Issue by klaasvw** [ONEAgency/drupical#7]
Make should check for the Vagrant version before attempting to provision. Currently 1.7.2 is not supported because of https://github.com/mitchellh/vagrant/issues/5180 

Als warn users with Vagrant version below 1.7.1 where the generated SSH key might not work.

**Comment by LeShadow** [comment]
Vagrant version is pinpointed now between 1.6.0 and 1.7.1.

**Comment by klaasvw** [comment]
We need an additional check on Vagrant up. If Vagrant version is higher than 1.7.1 an error message should be displayed and Vagrant shouldn't proceed;

**Comment by barickx** [comment]
check has been added in issue branch 35
